### ISSUE TITLE
Windows Problems

### ISSUE THREAD

**Issue by svenefftinge** [yang-tools/yang-vscode#1]
Apparently, the extension doesn't work on windows. To be tested

**Comment by kittaakos** [comment]
Confirmed:
```
[Info  - 1:17:10 PM] Starting validation for input: 'foo.yang'
[Error - 1:17:10 PM] Illegal character [:] in path at index 4: //\c:\Users\kittaakos\Desktop\yang.settings: java.nio.file.InvalidPathException: Illegal character [:] in path at index 4: //\c:\Users\kittaakos\Desktop\yang.settings
	at sun.nio.fs.WindowsPathParser.nextSlash(Unknown Source)
	at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
	at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
	at sun.nio.fs.WindowsPath.parse(Unknown Source)
	at sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
	at io.typefox.yang.settings.PreferenceValuesProvider.createPreferenceValues(PreferenceValuesProvider.java:101)
	at io.typefox.yang.settings.PreferenceValuesProvider.getPreferenceValues(PreferenceValuesProvider.java:63)
	at io.typefox.yang.utils.ExtensionProvider.getExtensions(ExtensionProvider.java:99)
	at io.typefox.yang.validation.ResourceValidator.validate(ResourceValidator.java:57)
	at org.eclipse.xtext.validation.ResourceValidatorImpl.validate(ResourceValidatorImpl.java:90)
	at io.typefox.yang.validation.ResourceValidator.validate(ResourceValidator.java:48)
	at org.eclipse.xtext.build.IncrementalBuilder$InternalStatefulIncrementalBuilder.validate(IncrementalBuilder.java:266)
	at org.eclipse.xtext.build.IncrementalBuilder$InternalStatefulIncrementalBuilder.lambda$launch$6(IncrementalBuilder.java:244)
	at org.eclipse.xtext.build.ClusteringStorageAwareResourceLoader.lambda$executeClustered$1(ClusteringStorageAwareResourceLoader.java:77)
	at org.eclipse.xtext.xbase.lib.internal.FunctionDelegate.apply(FunctionDelegate.java:42)
	at com.google.common.collect.Lists$TransformingRandomAccessList$1.transform(Lists.java:640)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at java.util.AbstractCollection.toArray(Unknown Source)
	at java.util.ArrayList.addAll(Unknown Source)
	at com.google.common.collect.Iterables.addAll(Iterables.java:350)
	at org.eclipse.xtext.build.ClusteringStorageAwareResourceLoader.executeClustered(ClusteringStorageAwareResourceLoader.java:80)
	at org.eclipse.xtext.build.BuildContext.executeClustered(BuildContext.java:55)
	at org.eclipse.xtext.build.IncrementalBuilder$InternalStatefulIncrementalBuilder.launch(IncrementalBuilder.java:251)
	at org.eclipse.xtext.build.IncrementalBuilder.build(IncrementalBuilder.java:399)
	at org.eclipse.xtext.build.IncrementalBuilder.build(IncrementalBuilder.java:384)
	at org.eclipse.xtext.ide.server.ProjectManager.doBuild(ProjectManager.java:115)
	at org.eclipse.xtext.ide.server.ProjectManager.doInitialBuild(ProjectManager.java:107)
	at org.eclipse.xtext.ide.server.BuildManager.doInitialBuild(BuildManager.java:149)
	at org.eclipse.xtext.ide.server.WorkspaceManager.refreshWorkspaceConfig(WorkspaceManager.java:148)
	at org.eclipse.xtext.ide.server.WorkspaceManager.initialize(WorkspaceManager.java:117)
	at org.eclipse.xtext.ide.server.LanguageServerImpl.lambda$initialize$9(LanguageServerImpl.java:286)
	at org.eclipse.xtext.ide.server.concurrent.RequestManager.lambda$runWrite$2(RequestManager.java:119)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
[Info  - 1:17:10 PM] Creating Deltas for changes. Deleted : [], Changed : [file:///c:/Users/kittaakos/Desktop/dugite-extra/foo.yang].
[Info  - 1:17:10 PM] Starting validation for input: 'foo.yang'
[Error - 1:17:10 PM] Illegal character [:] in path at index 4: //\c:\Users\kittaakos\Desktop\yang.settings: java.nio.file.InvalidPathException: Illegal character [:] in path at index 4: //\c:\Users\kittaakos\Desktop\yang.settings
	at sun.nio.fs.WindowsPathParser.nextSlash(Unknown Source)
	at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
	at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
	at sun.nio.fs.WindowsPath.parse(Unknown Source)
	at sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
	at io.typefox.yang.settings.PreferenceValuesProvider.createPreferenceValues(PreferenceValuesProvider.java:101)
	at io.typefox.yang.settings.PreferenceValuesProvider.getPreferenceValues(PreferenceValuesProvider.java:63)
	at io.typefox.yang.utils.ExtensionProvider.getExtensions(ExtensionProvider.java:99)
	at io.typefox.yang.validation.ResourceValidator.validate(ResourceValidator.java:57)
	at org.eclipse.xtext.validation.ResourceValidatorImpl.validate(ResourceValidatorImpl.java:90)
	at io.typefox.yang.validation.ResourceValidator.validate(ResourceValidator.java:48)
	at org.eclipse.xtext.build.IncrementalBuilder$InternalStatefulIncrementalBuilder.validate(IncrementalBuilder.java:266)
	at org.eclipse.xtext.build.IncrementalBuilder$InternalStatefulIncrementalBuilder.lambda$launch$6(IncrementalBuilder.java:244)
	at org.eclipse.xtext.build.ClusteringStorageAwareResourceLoader.lambda$executeClustered$1(ClusteringStorageAwareResourceLoader.java:77)
	at org.eclipse.xtext.xbase.lib.internal.FunctionDelegate.apply(FunctionDelegate.java:42)
	at com.google.common.collect.Lists$TransformingRandomAccessList$1.transform(Lists.java:640)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at java.util.AbstractCollection.toArray(Unknown Source)
	at java.util.ArrayList.addAll(Unknown Source)
	at com.google.common.collect.Iterables.addAll(Iterables.java:350)
	at org.eclipse.xtext.build.ClusteringStorageAwareResourceLoader.executeClustered(ClusteringStorageAwareResourceLoader.java:80)
	at org.eclipse.xtext.build.BuildContext.executeClustered(BuildContext.java:55)
	at org.eclipse.xtext.build.IncrementalBuilder$InternalStatefulIncrementalBuilder.launch(IncrementalBuilder.java:251)
	at org.eclipse.xtext.build.IncrementalBuilder.build(IncrementalBuilder.java:399)
	at org.eclipse.xtext.build.IncrementalBuilder.build(IncrementalBuilder.java:384)
	at org.eclipse.xtext.ide.server.ProjectManager.doBuild(ProjectManager.java:115)
	at org.eclipse.xtext.ide.server.BuildManager.internalBuild(BuildManager.java:182)
	at org.eclipse.xtext.ide.server.BuildManager.lambda$submit$0(BuildManager.java:130)
	at org.eclipse.xtext.ide.server.WorkspaceManager.lambda$didChangeFiles$2(WorkspaceManager.java:174)
	at org.eclipse.xtext.ide.server.LanguageServerImpl.lambda$didOpen$13(LanguageServerImpl.java:348)
	at org.eclipse.xtext.ide.server.concurrent.RequestManager.lambda$runWrite$2(RequestManager.java:122)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Sep 07, 2017 1:17:10 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint lambda$static$0
SEVERE: Internal error: java.nio.file.InvalidPathException: Illegal character [:] in path at index 4: //\c:\Users\kittaakos\Desktop\yang.settings
java.util.concurrent.CompletionException: java.nio.file.InvalidPathException: Illegal character [:] in path at index 4: //\c:\Users\kittaakos\Desktop\yang.settings
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
	at org.eclipse.xtext.ide.server.concurrent.RequestManager.lambda$null$0(RequestManager.java:84)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.nio.file.InvalidPathException: Illegal character [:] in path at index 4: //\c:\Users\kittaakos\Desktop\yang.settings
	at sun.nio.fs.WindowsPathParser.nextSlash(Unknown Source)
	at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
	at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
	at sun.nio.fs.WindowsPath.parse(Unknown Source)
	at sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
	at io.typefox.yang.settings.PreferenceValuesProvider.createPreferenceValues(PreferenceValuesProvider.java:101)
	at io.typefox.yang.settings.PreferenceValuesProvider.getPreferenceValues(PreferenceValuesProvider.java:63)
	at io.typefox.yang.ide.codelens.CodeLensService.computeCodeLenses(CodeLensService.java:102)
	at org.eclipse.xtext.ide.server.LanguageServerImpl.lambda$null$43(LanguageServerImpl.java:737)
	at org.eclipse.xtext.ide.server.WorkspaceManager.doRead(WorkspaceManager.java:284)
	at org.eclipse.xtext.ide.server.LanguageServerImpl.lambda$codeLens$44(LanguageServerImpl.java:741)
	at org.eclipse.xtext.ide.server.concurrent.RequestManager.lambda$null$0(RequestManager.java:78)
	... 4 more

[Error - 1:17:10 PM] Request textDocument/codeLens failed.
  Message: Internal error, please look at the server's logs.
  Code: -32603 
```

**Comment by svenefftinge** [comment]
fixed
